<MDScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(24)
        spacing: dp(16)
        adaptive_height: True
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        MDLabel:
            id: label
            text: "Привет, KivyMD 2.0!"
            halign: "center"
            font_style: "Title"
            role: "large"

        MDButton:
            style: "filled"
            pos_hint: {"center_x": 0.5}
            on_release: app.on_button_press()

            MDButtonText:
                text: "Нажми меня"